server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://34.64.173.178:3306/kookbee?serverTimezone=Asia/Seoul
    username: bee
    password: 1q2w3e4r
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  redis:
    lettuce:
      pool: # 클라이언트에서 Redis 서버와 연결을 관리하는 방법 중 하나
        max-active: 10 # pool에 할당될 수 있는 커넥션 최대수 (음수로 하면 무제한)
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 34.64.173.178
  application:
    name: user-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://34.64.69.238:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    # ???? ???? ???? ????? ??

